### ISSUE TITLE
feature request: save Report.comparisons as JSON

### ISSUE THREAD

**Issue by PaulLerner** [AmenRa/ranx#4]
Hi,

It’d be nice to be able to save a Report comparisons as a JSON file.
However, since it uses frozenset as keys, it is not JSON serializable.

Maybe you could add a method in https://github.com/AmenRa/ranx/blob/master/ranx/frozenset_dict.py to convert the `_map` to a JSON serializable dict, i.e. with `str` keys?
The `str` keys could be converted from the frozenset like: `', '.join(frozenset({'foo', 'bar'}))`

**Comment by AmenRa** [comment]
Hi, an export option for the Report class is already on my to-do list! :)

I will come back with a proposal so that we can discuss it before I implement the functionality.

**Comment by PaulLerner** [comment]
Looks great (and there was not so much delay :sweat_smile:)!

**Comment by AmenRa** [comment]
I added `Report.to_dict` and `Report.save`.
I updated `ranx` on PyPi with these new features.

Closing.

**Comment by PaulLerner** [comment]
I’m getting a "TypeError: Object of type int64 is not JSON serializable" which is probably coming from numba or numpy

**Comment by AmenRa** [comment]
Yeah, I know about that issue. I will look into it soon.

As a workaround, you can call `report.to_dict()` and save the dictionary as a `JSON` by yourself with the exact same code I wrote for the [`report.save`](https://github.com/AmenRa/ranx/blob/1c958bd5dbfd8e551750a292a165120e592d5c87/ranx/report.py#L190) function.

That issue it's kinda weird.

**Comment by PaulLerner** [comment]
for example in `transformers` they use:
```py
def denumpify_detensorize(metrics):
    """
    Recursively calls `.item()` on the element of the dictionary passed
    """
    if isinstance(metrics, (list, tuple)):
        return type(metrics)(denumpify_detensorize(m) for m in metrics)
    elif isinstance(metrics, dict):
        return type(metrics)({k: denumpify_detensorize(v) for k, v in metrics.items()})
    elif isinstance(metrics, np.generic):
        return metrics.item()
    elif is_torch_available() and isinstance(metrics, torch.Tensor) and metrics.numel() == 1:
        return metrics.item()
    return metrics
```

**Comment by AmenRa** [comment]
I will look into it soon.

**Comment by AmenRa** [comment]
Fixed in `0.1.10`. Sorry for the inconvenience.

**Comment by PaulLerner** [comment]
I’m still getting `TypeError: Object of type int64 is not JSON serializable`

**Comment by PaulLerner** [comment]
oops, looks like I was on the wrong branch, sorry about that
